### ISSUE TITLE
Action plan (Deadline Oct 8, Tool should be ready by then)

### ISSUE THREAD

**Issue by varshith15** [xlab-uiuc/slooo#3]
**Varshith:**
- [x] Test framework code for MongoDB
- [x] Test framework code for RethinkDB
- [x] Email Andrew to get clarity on the different types of experiments for TiDB
- [x] Port TiDB to the framework
- [ ] Test framework code for TiDB

**Andrei:**
- [ ] Port Redis

@TheEnthralled  Please fill/update in this part

**Yuxuan:**
- [ ] Finish Analyzing fail-slowness behavior of PolarDB
- [x] Test PolarDB on other distros
   Have tested PolarDB's compatibility on Ubuntu-20.04 (Hyper-V virtual machine)
- [ ] Port PolarDB to the framework

**Alex:**
@CodeTiger927 Please fill/update in this part

**Comment by tianyin** [comment]
@varshith15 @TheEnthralled Could you write about the team's action plan (including everyone), rather than each individual?

**Comment by tianyin** [comment]
1. We missed @CodeTiger927 

2. Please always add the right tag and assign to team mates.

**Comment by TheEnthralled** [comment]
8/30/2021: Sync-up
We just had a short update meeting amongst myself, @varshith15 , and @Essoz 

- Discussed the progress of porting Redis. It should be done by end of this week.
- Ideally want most everything due by next next week or so in order to start writing the paper.
- @varshith15  gave pointers on what should be changed in the code i.e
      Use the parser in https://github.com/xlab-uiuc/slooo/blob/main/run.xsh
      Use https://github.com/xlab-uiuc/slooo/blob/main/mongodb/temp.xsh as a template.
- Potential future goals/action plans
     Porting/implementing other databases (which ones in particular TBD)  
     Making the framework more generalizable

- Tool papers to look at
- We plan to get done with porting/testing Mongo, Rethink, Redis and Polar by next week
For TiDB need to sync with andrew (will mail him by today EOD)

**Comment by tianyin** [comment]
> Ideally want most everything due by next next week or so in order to start writing the paper.

This sounds quite ambitious.

But I think it is a good idea to start writing (especially the middle section) which helps us to have a more systematic look at the tool.

**Comment by Essoz** [comment]
9/7/2021: Sync-up
The three of us, @TheEnthralled  @varshith15  and @Essoz , just had a short update meeting, and we,
- Discussed the progress of the porting works (ideally want the porting work to be done in 3 or 4 days so we can work on what's left) 
    - @TheEnthralled is about to test the Redis code and 
    - @Essoz needs some modifications to the reusable utility functions. 
    - @varshith15 has just finished RethinkDB and is going to port TiDB.

- About how to make the framework more generic:
    - The slowness-inject function should be modified to support adding slowness to multiple TGIDs as a group (mainly for PolarDB because each PolarDB instance has multiple TGIDs)
    - Users should write functions to format the benchmark results into a unified format required by the framework.

- About the [Limplock](https://ucare.cs.uchicago.edu/pdf/socc13-limplock.pdf) paper that Tianyin recommended us to read
    - the link to the limpbench code has expired

- @tianyin About the auto-tuning functionality
    - have not started and will work on that after the porting work is done 
    - slowness inject functions should support controlling the slowness configs

**Comment by tianyin** [comment]
Thank you for the summary @Essoz !

> About how to make the framework more generic:

I like this! Please do think hard about the generality which will be one important section to discuss in the paper.

> the link to the limpbench code has expired

That's a good news 0_0 

The next question is whether there are more intellectual merit we can claim, other than their code dies and our code is alive (see #4 )

> have not started and will work on that after the porting work is done

Sure thing. It's more about an advance feature, instead of something essential or absolutely neceesary. 

I would suggest to first focus on making sure the Slooo framework is general and easy to use, which will be the foundation of the paper. If you can't validate the usefulness and usability, it does not matter whether you provide the auto-tuning feature or not.

**Comment by TheEnthralled** [comment]
Here's the new action plan for this week. Feel free to add to it or clarify things.

Andrei:

- [ ] Test Redis slooo code

Varshith:

- [ ] Test TiDB code

Yuxuan:

- [ ] Make more config-friendly interface for injecting/specifying fail-slow faults; "For example, a user can feed path to a specific slowness-config file when running run.xsh and then slow.xsh will read from that file when injecting slowness."

- [ ] Modify PolarDB code (use init_disk instead)

**Comment by tianyin** [comment]
@TheEnthralled Can you always close the previous one and open a new issue?  rather than putting new plans into the comment?The latter is hard to track.

**Comment by tianyin** [comment]
When you close the old issues, carry the unfinished items to the new issues.
